### ISSUE TITLE
Bug: Desktop IDE Shows Error for In-Line String Macro

### ISSUE THREAD

**Issue by imartincei** [Proektsoftbg/Calcpad#371]
The desktop IDE is showing an error when I'm using a macro that returns a string in the same line as an equation, even though it correctly interprets it in the output.

![image](https://github.com/user-attachments/assets/d2a2cf59-8afa-4609-b596-16c14a79654a)

![image](https://github.com/user-attachments/assets/3758cde2-eae5-4bd7-a413-102b5008c0e6)

**Comment by Proektsoftbg** [comment]
Yes, this is probably because it is glued to the units without space.
Calculations work because they perform deeper code analysis while the code highlighter does just some quick checks.
We will improve it in future.

**Comment by Proektsoftbg** [comment]
Hi!

This is fixed in version https://github.com/Proektsoftbg/Calcpad/releases/tag/v7.1.0.

**Comment by imartincei** [comment]
This issue still seems to be present. In addition, I noticed the same bug occurs when referencing a variable in the main space of the calculation from within a macro in the same file. 

![Image](https://github.com/user-attachments/assets/e0c3af45-e99b-49d7-8e05-0750f8aebab1)

![Image](https://github.com/user-attachments/assets/2b894c28-30dc-4a23-b784-6039c42b10dd)

These issues do not affect the output, but prevents tooltips and autocomplete when trying to access variables and functions. It also  highlights as an error in the editor which isn't ideal.
