### ISSUE TITLE
Debian packaging: No such file or directorye 1: ﻿#!/bin/sh

### ISSUE THREAD

**Issue by kalvdans** [Proektsoftbg/Calcpad#716]
It seems dotnet packaging inserts utf-16 byte order marks in the beginning of the start script:
```
$ xxd /usr/local/bin/calcpad
00000000: efbb bf23 212f 6269 6e2f 7368 0d0a 646f  ...#!/bin/sh..do
00000010: 746e 6574 202f 7573 722f 7368 6172 652f  tnet /usr/share/
00000020: 4361 6c63 7061 642f 4361 6c63 7061 642e  Calcpad/Calcpad.
00000030: 646c 6c20 2431 2024 3220 2433            dll $1 $2 $3
```

besides printing `: No such file or directorye 1: ﻿#!/bin/sh` there's no other harm.

The version is `Calcpad.7.4.1.deb`

**Comment by kalvdans** [comment]
I tried now! 7.5.6 give the same message, then fails with too old dotnet requirement. (7.5.6 requires dotnet 10, while 7.4.1 was happy with dotnet 8, dotnet 10 isn't released for Ubuntu 24.04 yet)

**Comment by Proektsoftbg** [comment]
Hi! I fixed it in version 7.5.7:
https://github.com/Proektsoftbg/Calcpad/releases/tag/v7.5.7

However, I am not quite willing to revert back to older .NET version. They will publish it sooner or later.

**Comment by kalvdans** [comment]
Thanks for fixing! The https://github.com/Proektsoftbg/Calcpad/releases/download/v7.5.7/Calcpad.7.5.7.deb link is still missing though.
